name: SCs Automation

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  update:
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'run-update' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run scs update
        uses: qaip/scs-action@v4
        with:
          ignore_empty: always
      - name: Remove trigger label
        if: ${{ github.event.label.name == 'run-update' }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'run-update'
